### ISSUE TITLE
Ошибка в api.http (node-tutorial-demos/04-logs-and-tests/09-supertest/ -- Модуль 4.9 учебника)

### ISSUE THREAD

**Issue by deniolp** [htmlacademy-nodejs/node-tutorial-demos#3]
В api.http есть такое:
`###       # Добавление новой книги  POST http://localhost:3000/api/books HTTP/1.1   Content-Type: "application/json"
{ "title": "The Dead Zone" } ###`

Вокруг application/json нужно убрать кавычки.

**Comment by AntonovIgor** [comment]
Спасибо! Поправил.
